apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: external-dns-cloudflare
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: vault
    target:
        name: external-dns-cloudflare
    data:
      - secretKey: token
        remoteRef:
            key: cloudflare
            property: token