app-template:
  image:
    repository: louislam/uptime-kuma
    tag: 1.23.15

  service:
    main:
      enabled: true
      ports:
        http:
          port: 3001

  # See more environment variables in the statping documentation
  # https://github.com/statping/statping/wiki/Config-with-.env-File
  env:
    TZ: "America/Chicago"
    NODE_EXTRA_CA_CERTS: /rootcert/ca.crt
    UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN: "0"
    UPTIME_KUMA_PORT: 3001

  ingress:
    main:
      enabled: true
      # ClassName: nginx
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/ssl-redirect: true
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        # cert-manager.io/revision-history-limit: "3"
        # cert-manager.io/duration: "2160h"
        # cert-manager.io/renew-before: "720h"
      hosts:
      - host: uptime.dev.techsecoms.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - uptime.dev.techsecoms.com
        secretName: up-cert-tls

  persistence:
    data:
      storageClass: "vsphere"
      accessMode: ReadWriteOnce
      skipuninstall: true
      size: "3Gi"
      mountPath: /app/data
      enabled: true
    rootcert:
      enabled: true
      type: secret
      name: up-cert-tls
  # serviceMonitor:
  ##   enabled: true

  probes:
    startup:
      enabled: false

    liveness:
      enabled: false

    readiness:
      enabled: false
