---
apiVersion: apps.projectsveltos.io/v1alpha1
kind: Cleaner
metadata:
    name: completed-jobs
spec:
    schedule: "* 0 * * *"
    resourcePolicySet:
        resourceSelectors:
          - kind: Job
            group: "batch"
            version: v1
            evaluate: |
                function evaluate()
                  hs = {}
                  hs.matching = false
                  if obj.status ~= nil then
                    if obj.status.completionTime ~= nil and obj.status.succeeded > 0 then
                      hs.matching = true
                    end
                  end
                  return hs
                end
    action: Delete