
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-superuser-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
  - secretKey: username
    remoteRef:
      key: secret/postgres-users/
      property: username
  - secretKey: password
    remoteRef:
      key: secret/postgres-users/
      property: password