{{- if and .Values.pooler.rw.enabled (gt (.Values.pooler.rw.instances | int) 0) (gt (.Values.connections.pooler | int) 0) }}
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: {{ include "cnpg-cluster.fullname" . }}-pooler-rw
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  cluster:
    name: {{ include "cnpg-cluster.fullname" . }}

  instances: {{ .Values.pooler.rw.instances }}
  type: rw

  pgbouncer:
    poolMode: {{ .Values.pooler.rw.mode }}
    parameters:
      max_client_conn: "{{ include "cnpg-cluster.pooler.maxClientConn" . }}"
      default_pool_size: "{{ include "cnpg-cluster.pooler.defaultPoolSize" . }}"
      max_db_connections: "{{ include "cnpg-cluster.pooler.maxDbConnections" . }}"

  template:
    spec:
      containers:
        - name: pgbouncer
          resources: {{ .Values.poolerResources | toYaml | nindent 12 }}
{{- end }}