apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ include "cnpg-cluster.fullname" . }}-object-store
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  instanceSidecarConfiguration:
    env:
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: when_required
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: when_required
  retentionPolicy: 15d
  configuration:
    endpointURL: {{ .Values.objectStore.endpoint }}
    destinationPath: "s3://{{ .Values.objectStore.bucketName }}/{{ .Release.Name }}/{{ include "cnpg-cluster.fullname" . }}-backups"
    s3Credentials:
      accessKeyId:
        name: {{ .Values.objectStore.s3CredentialsSecretName }}
        key: {{ .Values.objectStore.s3AccessKeyIdSecretKey }}
      secretAccessKey:
        name: {{ .Values.objectStore.s3CredentialsSecretName }}
        key: {{ .Values.objectStore.s3SecretAccessKeySecretKey }}
    data:
      compression: bzip2
      immediateCheckpoint: true  
      jobs: 2 
    wal:
      compression: bzip2
      maxParallel: 8

