apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
    name: gitlab-db
spec:
    name: gitlab
    owner: gitlab
    cluster:
        name: cnpg-cluster
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
    name: gitlab-registry-db
spec:
    name: gitlab-registry
    owner: gitlab
    cluster:
        name: cnpg-cluster