apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
    name: harbor-db
spec:
    name: harbor
    owner: harbor
    cluster:
        name: cnpg-cluster
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
    name: harbor-registry-db
spec:
    name: registry
    owner: harbor
    cluster:
        name: cnpg-cluster