apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: aws-credentials
spec:
    refreshInterval: 1h
    secretStoreRef:
        kind: ClusterSecretStore
        name: vault
    data:
      - secretKey: accessKeyId
        remoteRef:
            key: secret/minio/
            property: client_id
      - secretKey: secretAccessKey
        remoteRef:
            key: secret/minio/
            property: client_secret
