{{- if and .Values.monitoring.enabled .Values.monitoring.prometheusRule.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "cnpg-cluster.labels" . | nindent 4 }}
    {{- with .Values.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "cnpg-cluster.fullname" . }}-alert-rules
  namespace: {{ include "cnpg-cluster.namespace" . }}
spec:
  groups:
    - name: cloudnative-pg/{{ include "cnpg-cluster.fullname" . }}
      rules:

        {{- $instances := (default 1 .Values.instances) | int -}}

        {{- $ctx := dict
            "Values"       .Values
            "Release"      .Release
            "Chart"        .Chart
            "Files"        .Files
            "Capabilities" .Capabilities
            "Template"     .Template

            "namespace"    (include "cnpg-cluster.namespace" .)
            "cluster"      (include "cnpg-cluster.fullname" .)  
            "instances"    $instances
            "podSelector"  (printf "%s-([1-9][0-9]*)$" (include "cnpg-cluster.fullname" .))
            "excludeRules" (default (list) .Values.monitoring.prometheusRule.excludeRules)

            "labels" (dict
              "job"  "{{`{{ $labels.job }}`}}"
              "node" "{{`{{ $labels.node }}`}}"
              "pod"  "{{`{{ $labels.pod }}`}}")
            "prom"  (dict "value" "{{`{{ $value }}`}}")
          -}}
        {{- range $path, $_ := .Files.Glob "prometheus_rules/**.yaml" }}
        {{- with tpl ($.Files.Get $path) $ctx | nindent 10 | trim }}
        - {{ . }}
        {{- end }}
        {{- end }}
{{- end }}
