{{- if not (empty .Values.monitoring.customQueries) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cnpg-cluster.fullname" . }}-monitoring
  namespace: {{ .Release.Namespace }}   
  labels:
    cnpg.io/reload: ""
    {{- include "cnpg-cluster.labels" . | nindent 4 }}
data:
  custom-queries: |
    {{- range .Values.monitoring.customQueries }}
    {{ .name }}:
      query: {{ .query | quote }}
      metrics:
        {{- .metrics | toYaml | nindent 8 }}
    {{- end }}
{{- end }}