apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: wikijs-user-secret
spec:
    refreshInterval: 1h
    secretStoreRef:
        kind: ClusterSecretStore
        name: vault
    target:
        name: wikijs-user-secret
        creationPolicy: Owner
        template:
            metadata:
                labels:
                    cnpg.io/reload: ""
    data:
      - secretKey: username
        remoteRef:
            key: secret/wikijs-postgres-auth/
            property: username
      - secretKey: password
        remoteRef:
            key: secret/wikijs-postgres-auth/
            property: password