apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: velero-vsphere-config-secret
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: vault
    target:
        name: velero-vsphere-config-secret
        template:
            engineVersion: v2
            data:
                vsphere.conf: |-
                    [Global]
                    cluster-id = "dev-rke2-management-infra"
                    user = "{{`{{ .username }}`}}"
                    password = "{{`{{ .password }}`}}"
                    port = "443"
                    insecure-flag = "true"

                    [VirtualCenter "{{`{{ .vcenter_host }}`}}"]
                    datacenters = "{{`{{ .datacenter }}`}}"
    data:
      - secretKey: username
        remoteRef:
            key: /vsphere/
            property: username
      - secretKey: password
        remoteRef:
            key: /vsphere/
            property: password
      - secretKey: vcenter_host
        remoteRef:
            key: /vsphere/
            property: vcenter_host
      - secretKey: datacenter
        remoteRef:
            key: /vsphere/
            property: datacenter
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: cloud-credentials
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: vault
    target:
        name: cloud-credentials
        template:
            engineVersion: v2
            data:
                vsphere.conf: |-
                    [Global]
                    cluster-id = "dev-rke2-management-infra"
                    user = "{{`{{ .username }}`}}"
                    password = "{{`{{ .password }}`}}"
                    port = "443"
                    insecure-flag = "true"

                    [VirtualCenter "{{`{{ .vcenter_host }}`}}"]
                    datacenters = "{{`{{ .datacenter }}`}}"
    data:
      - secretKey: username
        remoteRef:
            key: /vsphere/
            property: username
      - secretKey: password
        remoteRef:
            key: /vsphere/
            property: password
      - secretKey: vcenter_host
        remoteRef:
            key: /vsphere/
            property: vcenter_host
      - secretKey: datacenter
        remoteRef:
            key: /vsphere/
            property: datacenter