app-template:
  controllers:
    main:
      annotations:
        reloader.stakater.com/auto: "true"

      pod:
        enableServiceLinks: false

      containers:
        main:
          image:
            repository: ghcr.io/actualbudget/actual-server
            tag: 25.1.0
          resources:
            requests:
              cpu: 12m
              memory: 128M
            limits:
              memory: 512M

  service:
    main:
      ports:
        http:
          port: 5006

  ingress:
    main:
      enabled: true
      className: "nginx"
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Tools
        gethomepage.dev/icon: actual
        gethomepage.dev/name: Actual
        cert-manager.io/cluster-issuer: letsencrypt-prod
        cert-manager.io/revision-history-limit: "3"
        cert-manager.io/duration: "2160h"
        cert-manager.io/renew-before: "720h"
      hosts:
      - host: "actual.dev.techsecoms.com"
        paths:
        - path: /
          service:
            name: main
            port: http
      tls:
      - hosts:

        - actual.dev.techsecoms.com
        secretName: actual-tls

  persistence:
    data:
      enabled: true
      storageClass: "vsphere"
      size: 5Gi
      accessMode: ReadWriteOnce
      advancedMounts:
        main:
          main:
          - path: /data
