wikijs:
  controllers:
    main:
      # -- Controller type
      type: deployment
      replicas: 1
      containers:
        app:
          image:
            # -- Image repository
            repository: ghcr.io/requarks/wiki
            # -- Image pull policy
            pullPolicy: IfNotPresent
            # -- Image tag
            tag: 2.5.308
          env:
          - name: TZ
            value: "America/Chicago"
          - name: DB_TYPE
            value: "postgres"
          - name: DB_HOST
            value: "cnpg-cluster-rw.cnpg-system.svc.cluster.local"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "wikijs"
          - name: DB_USER
            value: "wikijs"
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: wikijs-user-secret
                key: password
          # DB_TYPE: postgres
          # DB_HOST:
          # DB_PORT:
          # DB_NAME:
          # DB_USER:
          # DB_PASS:

      resources: {}
        # limits:
        #   cpu: 100m
        #   memory: 128Mi
        # requests:
        #   cpu: 100m
        #   memory: 128Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 3000

  data:
    storageClass: nfs-csi
    accessModes:
    - ReadWriteMany
    size: 10Gi

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        cert-manager.io/revision-history-limit: "3"
        external-dns.alpha.kubernetes.io/enabled: "true"
        cert-manager.io/duration: "2160h"
        cert-manager.io/renew-before: "720h"
      hosts:
      - host: &host-main "wiki.prod.techsecom.io"
        paths:
        - path: /
          pathType: Prefix
          service:
            identifier: main
            port: http
      tls:
      - secretName: wiki-tls
        hosts:
        - *host-main
  postgresql:
    enabled: false
    architecture: standalone
    primary:
      persistence:
        enabled: true
        storageClass: nfs-csi
        accessModes:
        - ReadWriteMany
        size: 8Gi
    auth:
      enablePostgresUser: false
      username: wikijs
      password: changeme
      database: wikijs
      existingSecret: ""
      secretKeys:
        userPasswordKey: ""
