{{- if .Values.eso.enabled }}
{{- $secretName := .Values.eso.secretName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/redis
        metadataPolicy: None
        property: REDIS_PASSWORD
{{- end }}
