apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: idp-provider
spec:
    refreshInterval: 1h
    secretStoreRef:
        kind: ClusterSecretStore
        name: vault
    target:
        name: idp-provider
        creationPolicy: Owner
        template:
            type: Opaque
            engineVersion: v2
            # data:
            #     config: |
            #         [default]
            #         access_key = "{{ .MINIO_ACCESS_KEY }}"
            #         secret_key = "{{ .MINIO_SECRET_KEY }}"
            #         bucket_location = us-east-1
            #         multipart_chunk_size_mb = 128 
            #         regionendpoint: "http://minio.minio.svc.cluster.local:9000"
    data:
      - secretKey: provider
        remoteRef:
            key: secret/gitlab
            property: saml-idp-provider