apiVersion: v1
data:
    password: VGVjaHNlY29tcy1AcmtlMg==
kind: Secret
metadata:
    labels:
        app: gitlab
    name: gitlab-initial-root-password
    # namespace: gitlab-operator
type: Opaque
---
apiVersion: v1
data:
    password: TldSalpHUTBZMkkyWWpGaU1ERmpOakZrWlRNM1kySXpZbVEzTldNM1pqUUs=
    postgres-password: WVdWbVlXUTNOVE0wT0RRMFlXSXhORFl5WVdNeFpETm1NREkwTUdWaVlqa0s=
    repmgr-password: TTJVNE1XSTBaREV4T1RnelpXSTFaRFUxWXpoaVlXUmtPR0V5TkRNMU9EQUs=
    admin-password: TldSalpHUTBZMkkyWWpGaU1ERmpOakZrWlRNM1kySXpZbVEzTldNM1pqUUs=
kind: Secret
metadata:
    name: postgresql-secret
    namespace: gitlab
---
apiVersion: v1
data:
    password: TldSalpHUTBZMkkyWWpGaU1ERmpOakZrWlRNM1kySXpZbVEzTldNM1pqUUs=
    postgres-password: WVdWbVlXUTNOVE0wT0RRMFlXSXhORFl5WVdNeFpETm1NREkwTUdWaVlqa0s=
    repmgr-password: TTJVNE1XSTBaREV4T1RnelpXSTFaRFUxWXpoaVlXUmtPR0V5TkRNMU9EQUs=
    admin-password: TldSalpHUTBZMkkyWWpGaU1ERmpOakZrWlRNM1kySXpZbVEzTldNM1pqUUs=
kind: Secret
metadata:
    name: repmgr-secret
    namespace: gitlab
---
apiVersion: v1
data:
    password: TldSalpHUTBZMkkyWWpGaU1ERmpOakZrWlRNM1kySXpZbVEzTldNM1pqUUs=
    postgres-password: WVdWbVlXUTNOVE0wT0RRMFlXSXhORFl5WVdNeFpETm1NREkwTUdWaVlqa0s=
    repmgr-password: TTJVNE1XSTBaREV4T1RnelpXSTFaRFUxWXpoaVlXUmtPR0V5TkRNMU9EQUs=
    admin-password: TldSalpHUTBZMkkyWWpGaU1ERmpOakZrWlRNM1kySXpZbVEzTldNM1pqUUs=
kind: Secret
metadata:
    name: pgpool-secret
    namespace: gitlab