apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
  - secretKey: REDIS_PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/redis
      metadataPolicy: None
      property: REDIS_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-s3-creds
  namespace: gitlab
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: minio-s3-creds
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        storage.yml: |
          provider: AWS
          region: us-east-1
          aws_access_key_id: "{{ .MINIO_ACCESS_KEY }}"
          aws_secret_access_key: "{{ .MINIO_SECRET_KEY }}"
          aws_signature_version: 4
          host: "s3.prod.techsecom.io"
          endpoint: "http://minio.minio.svc.cluster.local:9000"
          path_style: true
  data:
  - secretKey: MINIO_ACCESS_KEY
    remoteRef:
      # Vault KV v2 path (relative to the kv mount configured above)
      key: secret/minio/
      property: postgres_user
  - secretKey: MINIO_SECRET_KEY
    remoteRef:
      key: secret/minio/
      property: postgres_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-s3-config
  namespace: gitlab
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: registry-s3-config
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        registry-s3.yml: |
          s3:
            bucket: gitlab-registry
            accesskey: "{{ .MINIO_ACCESS_KEY }}"
            secretkey: "{{ .MINIO_SECRET_KEY }}"
            region: "us-east-1"
            regionendpoint: "http://minio.minio.svc.cluster.local:9000"
            v4auth: true
  data:
  - secretKey: MINIO_ACCESS_KEY
    remoteRef:
      # Vault KV v2 path (relative to the kv mount configured above)
      key: secret/minio/
      property: postgres_user
  - secretKey: MINIO_SECRET_KEY
    remoteRef:
      key: secret/minio/
      property: postgres_password
---
apiVersion: v1
kind: Secret
metadata:
  name: idp-provider
data:
  provider: bmFtZTogJ3NhbWwnCmxhYmVsOiAnT3VyIFNBTUwgUHJvdmlkZXInCmFyZ3M6CiAgYXNzZXJ0aW9uX2NvbnN1bWVyX3NlcnZpY2VfdXJsOiAnaHR0cHM6Ly9naXRsYWIucHJvZC50ZWNoc2Vjb21zLmNvbS91c2Vycy9hdXRoL3NhbWwvY2FsbGJhY2snCiAgaWRwX2NlcnRfZmluZ2VycHJpbnQ6ICc1NDo4NTpCMzo3NToyMzo1NjoxMjpGQzowQTo2Qjo0MzpEMjpDMToxQjoyNDo3NDpBNTpDODpDNTpCNicKICBpZHBfc3NvX3RhcmdldF91cmw6ICdodHRwczovL3RlY2hzZWNvbXMudWkuY29tL2d3L2lkcC9hcGkvdjEvcHVibGljL3Nzby9zYW1sL2IxN2I4MzFmLTk0MTktNDJkOC05MGM0LTNjYjhmMDYwZjhmZScKICBpc3N1ZXI6ICdodHRwczovL2dpdGxhYi5wcm9kLnRlY2hzZWNvbXMuY29tJwoKICBhdHRyaWJ1dGVfc3RhdGVtZW50czoKICAgIGVtYWlsOiBbICd1cm46b2lkOjEuMy42LjEuNC4xLjU5MjMuMS4xLjEuNicgXSAjIEVuc3VyZSBHaXRMYWIgbWFwcyBlbWFpbCBjb3JyZWN0bHkKICAgIGZpcnN0X25hbWU6IFsgJ3VybjpvaWQ6Mi41LjQuNDInIF0KICAgIGxhc3RfbmFtZTogWyAndXJuOm9pZDoyLjUuNC40JyBdCiAgICBncm91cHM6IFsgJ0dyb3VwcycgXQoKICAjIHJlcXVpcmVkX2dyb3VwczogWyAnRGV2ZWxvcGVycycsICdGcmVlbGFuY2VycycsICdBZG1pbnMnLCAnQXVkaXRvcnMnIF0KICBuYW1lX2lkZW50aWZpZXJfZm9ybWF0OiAndXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOm5hbWVpZC1mb3JtYXQ6dHJhbnNpZW50JwoKICAjIHVpZF9hdHRyaWJ1dGU6ICdodHRwczovL3d3dy51aS5jb20vMjViMWY3ZDgtMDBiMS00Y2MxLTg4NGYtNzc3ZTAxNTMyN2ViJwogIGlkcF9jZXJ0OiB8CiAgICAtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0gTUlJRVVUQ0NBem1nQXdJQkFnSUlkanpEMEtVOWQ1c3dEUVlKS29aSWh2Y05BUUVMQlFBd2dhb3hDekFKQmdOViBCQVlUQWtOT01SRXdEd1lEVlFRSUV3aFRhR1Z1V21obGJqRVNNQkFHQTFVRUJ4TUpSM1ZoYm1ka2IyNW5NUXN3IENRWURWUVFLRXdKWFV6RVVNQklHQTFVRUN4TUxkMjl5YXkxemRHRmphM014VVRCUEJnTlZCQU1UU0RZd1pEZGsgWXpCa0xUSmxNMll0TkRkbE5DMDVZekkxTFdGa01qSTRNekZtTkdaaE1XSXhOMkk0TXpGbUxUazBNVGt0TkRKayBPQzA1TUdNMExUTmpZamhtTURZd1pqaG1aVEFlRncweU5UQXlNRFl3TmpNeE5UbGFGdzB6TlRBeU1EWXdOak14IE5UbGFNSUdxTVFzd0NRWURWUVFHRXdKRFRqRVJNQThHQTFVRUNCTUlVMmhsYmxwb1pXNHhFakFRQmdOVkJBY1QgQ1VkMVlXNW5aRzl1WnpFTE1Ba0dBMVVFQ2hNQ1YxTXhGREFTQmdOVkJBc1RDM2R2Y21zdGMzUmhZMnR6TVZFdyBUd1lEVlFRREUwZzJNR1EzWkdNd1pDMHlaVE5tTFRRM1pUUXRPV015TlMxaFpESXlPRE14WmpSbVlURmlNVGRpIE9ETXhaaTA1TkRFNUxUUXlaRGd0T1RCak5DMHpZMkk0WmpBMk1HWTRabVV3Z2dFaU1BMEdDU3FHU0liM0RRRUIgQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURJUkJ3SVBQcmYyVGVTU1d6anhCbGZmemZNWnhCMkNiOWJyK2xEY00zWiBleldlZndrNG9Xb3pUc3FrN0Q5OXJrblBOTEdXcmZqeWVMK2FuaHpHRmo5YTI4amRnZUJGQUxFZkhLTGw2N1lEIEtmZXk3TXZYcmtzVGpSRWlkTkhaSFZVcm9xb3k0N2lrc1BUcEM0VG1ub29NWjhaaXZ5dFNCSUFGNVRMWU9NUlAgYzdiTnNEWFJHUzFNNW5nZ3lKM2I2UnBCUndFelUwZFJGLzMwSjhDQjVUcFNiRE4weXdPNlJLUkNSYzVMaE41MiBLSDBIc3dma1Z6aEN4VTJPNmFkQnE4WFBTRlA1SEEwTmxmb1BhbGFoTFVURmNKV1NEREluQ1ZqNnphdW9WY0lXIDZsaG84dkNHbGtWeXVteVhIT0x1NnloSzAxRzhackdEa0g2aHF2NjNJanAxQWdNQkFBR2plVEIzTUE0R0ExVWQgRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFnWUlLd1lCQlFVSEF3RXdEd1lEVlIwVCBBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVSndMdWs3V3lJVkVYdlZicVV6SW5CNXhqeXVBd0ZnWURWUjBSIEJBOHdEWUVMYUdWc2NFQjFhUzVqYjIwd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDc1FLY0hMSDQ0WnE1dUIgZFZVTjlLNzlXWTJvTndYTWhwaGJxS01FdGNYS0x4WkdFUHN3cGdKcnRFMXdPZkt0ejlaWVc1VjNmT0hkQ1BJNCBlQjE5K3lEd0s2VXltQUZ2TXRLSEc2WnY2ZzdaWUdvbWkzSHN5RjBuS29kMWh5TGh5Y2pWN1pENjYxNm5rNm1PIHBhbU9reWM1a2ZlY0tXNWRlQ0J2dm9iZHJ5ckZIeUFOVFlEUXcrZ3J5QU9OR04wNXFyd1RieXRBd05YbDlGNk4gZmhycURtYmdCbE5iV0lOc0dMWDh5SFgxT0I2aXByQVF0cHJ2dzlrd0VqZnl4VVpWY2V5YWdoOXVRdmp2Tm5zdiBJVXp1ZkJvVDZGY29qSVlxTXBkeWFKUW5yeE1pRG5xNVZOd0J3MVl5dzducXUrOGZzbDZNVDM3RFVTMzJUbmZEIC9COXptb009IC0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-initial-root-password
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: gitlab-initial-root-password
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: ""
  data:
  - secretKey: password
    remoteRef:
      key: secret/gitlab
      property: gitlab-initial-root-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: postgresql-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: ""
  data:
  - secretKey: username
    remoteRef:
      key: secret/gitlab/
      property: dbusername
  - secretKey: password
    remoteRef:
      key: secret/gitlab/
      property: dbpassword
---
apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab
spec:
  chart:
    values:
      installCertmanager: false
      postgresql:
        install: false
      nginx-ingress:
        enabled: false
      gitlab:
        gitlab-shell:
          maxReplicas: 6
          minReplicas: 1
        sidekiq:
          maxReplicas: 6
          minReplicas: 1
          resources:
            requests:
              cpu: 500m
              memory: 1000M
        webservice:
          maxReplicas: 2
          minReplicas: 1
          resources:
            requests:
              cpu: 500m
              memory: 1500M
      global:
        hosts:
          domain: techsecom.io
          hostSuffix: null
          gitlab:
            name: gitlab.prod.techsecom.io
            https: true
        appConfig:
          object_store:
            enabled: true
            connection:
              secret: minio-s3-creds
          # artifacts: 
          #   bucket: gitlab-artifacts
        registry:
          bucket: gitlab-registry
        minio:
          enabled: false
        ingress:
          configureCertmanager: false
          tls:
            secretName: null
        psql:
          main:
            host: cnpg-cluster-rw.cnpg-system.svc.cluster.local
            port: "5432"
            database: "gitlabhq-production"
            username: "gitlab"
            password:
              useSecret: true
              secret: postgresql-secret
              key: "password"
          ci:
            host: cnpg-cluster-rw.cnpg-system.svc.cluster.local
            port: "5432"
            database: gitlabhq-roduction-ci
            username: gitlab
            password:
              useSecret: true
              secret: postgresql-secret
              key: password
      registry:
        storage:
          secret: registry-s3-config
      redis:
        resources:
          requests:
            cpu: 100m
    version: 9.4.2
