installCertmanager: false
postgresql:
  install: false
nginx-ingress:
  enabled: false

global:
  hosts:
    domain: techsecom.io
    hostSuffix: null
    gitlab:
      name: gitlab.prod.techsecom.io
      https: true
  appConfig:
    object_store:
      enabled: true
      proxy_download: false
      connection: {}
        # secret: minio-s3-creds
        # key: connection

    lfs:
      enabled: true
      proxy_download: true
      bucket: git-lfs
      connection: {}
        # secret: minio-s3-creds
        # key: connection
    artifacts:
      enabled: true
      proxy_download: true
      bucket: gitlab-artifacts
      connection: {}
        # secret:
        # key:
    uploads:
      enabled: true
      proxy_download: true
      bucket: gitlab-uploads
      connection: {}
        # secret:
        # key:
    packages:
      enabled: true
      proxy_download: true
      bucket: gitlab-packages
      connection: {}
    externalDiffs:
      enabled: false
      when:
      proxy_download: true
      bucket: gitlab-mr-diffs
      connection: {}
    terraformState:
      enabled: true
      bucket: gitlab-terraform-state
      connection: {}
    ciSecureFiles:
      enabled: true
      bucket: gitlab-ci-secure-files
      connection: {}
    dependencyProxy:
      enabled: true
      proxy_download: true
      bucket: gitlab-dependency-proxy
      connection: {}

    backups:
      bucket: gitlab-backups
      tmpBucket: tmp

  minio:
    enabled: false
  ingress:
    configureCertmanager: false
    tls:
      secretName: null
  psql:
    main:
      host: cnpg-cluster-rw.cnpg-system.svc.cluster.local
      port: 5432
      database: gitlabhq-production
      username: gitlab
      password:
        useSecret: true
        secret: postgresql-secret
        key: password
    ci:
      host: cnpg-cluster-rw.cnpg-system.svc.cluster.local
      port: 5432
      database: gitlabhq-roduction-ci
      username: gitlab
      password:
        useSecret: true
        secret: postgresql-secret
        key: password
gitlab:
  toolbox:
    backups:
      objectStorage:
        config:
          secret: s3cmd-config
          key: config
  gitlab-shell:
    maxReplicas: 6
    minReplicas: 1
  sidekiq:
    maxReplicas: 6
    minReplicas: 1
    resources:
      requests:
        cpu: 500m
        memory: 1000M
  webservice:
    maxReplicas: 2
    minReplicas: 1
    resources:
      requests:
        cpu: 500m
        memory: 1000M
  gitlab-pages:
    maxReplicas: 1
    minReplicas: 1
    resources:
      requests:
        cpu: 300m
        memory: 1000M
registry:
  storage:
    secret: registry-s3-config
    key: registry
redis:
  resources:
    requests:
      cpu: 100m
