prometheus-pushgateway:
  fullnameOverride: pushgateway

  ingress:
    enabled: true
    className: nginx
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Monitoring
      gethomepage.dev/icon: prometheus
      gethomepage.dev/name: Pushgateway
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      cert-manager.io/revision-history-limit: "3"
      cert-manager.io/duration: "2160h"
      cert-manager.io/renew-before: "720h"

    hosts:
    - pushgateway.dev.techsecoms.com
    tls:
    - hosts:
      - pushgateway.dev.techsecoms.com
      secretName: pushgateway-cert-tls

  serviceMonitor:
    enabled: true
    additionalLabels:
      app: prometheus-operator
      release: prometheus
