apiVersion: v2
name: it-tools
description: A Helm chart for it-tools

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# The chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 2.2.0

# Version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "2024"

dependencies:
- name: it-tools
  version: 2.2.0
  repository: https://charts.plcnk.net
