---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#
it-tools:
  controllers:
    main:
      # -- Controller type
      type: deployment
      # -- Number of desired pods
      replicas: 1
      containers:
        app:
          image:
            # -- Image repository
            repository: ghcr.io/corentinth/it-tools
            # -- Image pull policy
            pullPolicy: IfNotPresent

          env:
            TZ: CST

          securityContext:
            # -- Mount the container's root filesystem as read-only
            readOnlyRootFilesystem: true
            # -- Disable privilege escalations
            allowPrivilegeEscalation: false
            # -- Drop all capabilities
            capabilities:
              drop:
              - ALL

      pod:
        securityContext:
          # -- Run container as a non-root user
          runAsNonRoot: true
          # -- Run as `nobody` user
          runAsUser: 65534
          # -- Run as `nobody` group
          runAsGroup: 65534
          # -- Volume binds will be granted to `nobody` group
          fsGroup: 65534

      # -- Set the resource requests / limits for the container.
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi

  # -- Configure the services for the chart here.
  # @default -- See [values.yaml](./values.yaml)
  service:
    main:
      controller: main
      ports:
        http:
          port: 8080

  # -- Configure persistence for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  persistence:
    data:
      enabled: true
      retain: true
      storageClass: "nfs-csi"
      accessMode: ReadWriteMany
      size: 1Gi

  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See [values.yaml](./values.yaml)
    main:
      enabled: true
      className: "nginx"
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: IT-Tools
        gethomepage.dev/description: Various tools for IT
        gethomepage.dev/group: Services
        gethomepage.dev/icon: it-tools-light.png
        gethomepage.dev/href: https://tools.prod.techsecom.io
        gethomepage.dev/siteMonitor: https://tools.prod.techsecom.io
        external-dns.alpha.kubernetes.io/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
      - host: tools.prod.techsecom.io
        paths:
        - path: /
          pathType: Prefix
          service:
            identifier: main
            port: http
      tls:
      - secretName: it-tools-tls
        hosts:
        - tools.prod.techsecom.io
