apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: elastic-system-cert-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elastic-system-cert-ca
spec:
  isCA: true
  commonName: elastic-system-cert-ca
  secretName: root-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    kind: ClusterIssuer
    name: elastic-system-cert-issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: elastic-system-ca-issuer
spec:
  ca:
    secretName: root-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch-es-cert
spec:
  isCA: false
  dnsNames:
    - elasticsearch-es-http
    - elasticsearch.dev.techsecoms.com
    - elasticsearch-es-http.elastic-system.svc
    - elasticsearch-es-http.elastic-system.svc.cluster.local
  subject:
    organizations:
      - elasticsearch
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    kind: Issuer
    name: elastic-system-ca-issuer
  secretName: elasticsearch-es-cert
