{{- if .Values.eso.enabled }}
{{- $secretName := .Values.eso.secretName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-minio-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.eso.secretStoreName }}
  data:
  - secretKey: MINIO_ACCESS_KEY
    remoteRef:
      key: secret/postgres-users/
      property: username
  - secretKey: MINIO_SECRET_KEY
    remoteRef:
      key: secret/postgres-users/
      property: password