{{- if .Values.eso.enabled }}
{{- $secretName := .Values.eso.secretName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-superuser-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.eso.secretStoreName }}
  data:
  - secretKey: username
    remoteRef:
      key: {{ $secretName }}
      property: dbusername
  - secretKey: password
    remoteRef:
      key: {{ $secretName }}
      property: dbpassword