apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: main
  source:
    repoURL: https://github.com/Techsecom/argocd-gitops.git
    path: gitops/apps-of-apps/
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
