---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: vault-secrets
    namespace: vault
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: vault
    target:
        name: vault-secrets
    data:
      - secretKey: OIDC_CLIENT_SECRET
        remoteRef:
            key: /vault
            property: oidc-client-secret
      - secretKey: OIDC_DISCOVERY_URL
        remoteRef:
            key: vault
            property: oidc-discovery-url
