{{- if .Values.eso.enabled }}
{{- $secretName := .Values.eso.secretName }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
  - secretKey: username
    remoteRef:
      key: secret/keycloak
      property: username
  - secretKey: password
    remoteRef:
      key: secret/keycloak
      property: password
{{- end }}
