{{- if .Values.eso.enabled }}
{{- $secretName := .Values.eso.secretName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.eso.secretStoreName }}
  data:
  - secretKey: HARBOR_ADMIN_PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/harbor
      metadataPolicy: None
      property: HARBOR_ADMIN_PASSWORD
  - secretKey: secretKey
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/harbor
      metadataPolicy: None
      property: secretKey
  - secretKey: REGISTRY_HTPASSWD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/harbor
      metadataPolicy: None
      property: REGISTRY_HTPASSWD
  - secretKey: REGISTRY_PASSWD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/harbor
      metadataPolicy: None
      property: REGISTRY_PASSWD
{{- end }}
