{{ if and .Values.oidc.enabled .Values.eso.enabled  }}
{{- $secretName := .Values.eso.secretName }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-client-harbor-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.eso.secretStoreName }}
  data:
  # should be clientSecret, since keycloak operator uses this key for secret
  - secretKey: clientSecret
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $secretName }}
      metadataPolicy: None
      property: harbor.oidcClientSecret
{{ end }}
