{{- if .Values.eso.enabled }}
{{- $secretName := .Values.eso.secretName }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: centralized-minio-users
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        username1: |
          username={{ printf "{{ .REGISTRY_STORAGE_S3_ACCESSKEY }}" }}
          password={{ printf "{{ .REGISTRY_STORAGE_S3_SECRETKEY }}" }}
          disabled=false
          policies=harbor
          setPolicies=false
        username2: |
          username={{ printf "{{ .REGISTRY_STORAGE_S3_ACCESSKEY }}" }}
          password={{ printf "{{ .REGISTRY_STORAGE_S3_SECRETKEY }}" }}
          disabled=false
          policies=rke2-local-cluster
          setPolicies=false

  data:
    - secretKey: REGISTRY_STORAGE_S3_ACCESSKEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/harbor
        metadataPolicy: None
        property: internal_username
    - secretKey: REGISTRY_STORAGE_S3_SECRETKEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/harbor
        metadataPolicy: None
        property: internal_password
{{- end }}
