apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: vault-ca
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: vault
    target:
        name: vault-ca
    data:
      - secretKey: api-token
        remoteRef:
            key: cloudflare
            property: token