# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: kured-notification
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: vault
#     target:
#     name: kured-notification
#     creationPolicy: Owner
#   data:
#   - secretKey: slack_webhook_url
#     remoteRef:
#       key: secret/kured-slack
#       property: webhook
#   - secretKey: slack-kured_notification
#     remoteRef:
#       key: secret/slack
#       property: kured-notification
# ---
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: kured-secret
#   namespace: kured
#   labels:
#     argocd.argoproj.io/instance: kured
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: Vault
#   target:
#     name: secret/kured-secret/        # 👈 Name of the Kubernetes Secret created
#     creationPolicy: Owner
#   data:
#     - secretKey: username
#       remoteRef:
#         key: secret/kured-secret/
#         property: username                # 👈 fixed typo from "usename" → "username"
#     - secretKey: password
#       remoteRef:
#         key: secret/kured-secret/
#         property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-webhook-url
  namespace: kured
  labels:
    argocd.argoproj.io/instance: kured
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
  - secretKey: channel
    remoteRef:
      key: secret/slack-webhook-url/
      property: channel
  - secretKey: webhook-url
    remoteRef:
      key: secret/slack-webhook-url/
      property: webhook-url