---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    bandwidthManager:
      enabled: true
    kubeProxyReplacement: true
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    systemDefaultIngressClass: nginx
    l2announcements:
      enabled: true
    # localRedirectPolicies:
    #   # -- Enable local redirect policies.
    #   enabled: true
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList:
        - "10.42.0.0/16"
        clusterPoolIPv4MaskSize: 24
    socketLB:
      enabled: false
      # -- Disable socket lb for non-root ns. This is used to enable Istio routing rules.
      hostNamespaceOnly: false
    # Required for multus
    cni:
      exclusive: false
    # Tells Cilium what the main IP is
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
    externalIPs:
      enabled: true
    enableRuntimeDeviceDetection: true
    devices: 
    - enp11s0f1np1
    - wg0
    - enp0s31f6
    - br0
    operator:
      replicas: 2
    # agent: true
    hubble:
      enabled: true
      metrics:
        enabled:
        - dns
        - drop
        - tcp
        - flow
        - port-distribution
        - icmp
        - http
        enableOpenMetrics: true
        serviceMonitor:
          enabled: false
        service:
          enabled: true

      relay:
        enabled: true
        metrics:
          enabled: true
          port: 9965
          protocol: TCP
          targetPort: 9965
          serviceMonitor:
            enabled: false
          service:
            enabled: true
      ui:
        enabled: true
        service:
          type: NodePort
          nodePort: 31647
