apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-proxy-config
  namespace: kube-system
data:
  Corefile: |
    .:53 {
      errors
      health
      forward . 10.43.0.10 # Forward to kube-system/kube-dns
      loop
      loadbalance
    }
