---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    bandwidthManager:
      enabled: true
    kubeProxyReplacement: true
    l2announcements:
      enabled: true
    socketLB:
      enabled: true
      # -- Disable socket lb for non-root ns. This is used to enable Istio routing rules.
      hostNamespaceOnly: true
    # Required for multus
    cni:
      exclusive: false
    # Tells Cilium what the main IP is
    k8sServiceHost: 10.10.10.2
    k8sServicePort: 6443
    externalIPs:
      enabled: true
    devices: 
    - enp11s0f1np1
    - wg0
    - enp0s31f6
    - br0
    - 
    operator:
      replicas: 2
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
