apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-apps
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
  - list:
      elements:
      - name: kube-cleanup-operator
        serverSideApply: true
        namespace: kube-cleanup
      # - name: cert-manager
      #   namespace: cert-manager
      #   serverSideApply: true
      # - name: ingress-nginx
      #   namespace: ingress-nginx
      #   serverSideApply: true
      # - name: argocd
      #   namespace: argocd
      #   serverSideApply: true

      # - name: cloudnative-pg-cluster
      #   namespace: cnpg-pg-cluster
      #   serverSideApply: true
      # # - name: ghost
      # - name: go-healthcheck
      # - name: prometheus-operator
      #   namespace: monitoring
      #   serverSideApply: true
      # - name: eck-stack
      #   namespace: elastic-system
      #   serverSideApply: true

  template:
    metadata:
      name: "{{ .name }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "."
        # notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1001726711150"
        # argocd.argoproj.io/compare-options: '{{ printf "%s=%s" "ServerSideDiff" (dig "serverSideDiff" "false" . | toString) }}'
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/donydonald1/rke2-baremetal-tf-ansible.git
        targetRevision: HEAD
        path: "gitops/infrastructure/{{ .name }}"
        # plugin:
        #   name: avp-directory-include
        # env:
        #   - name: FILE_NAME
        #     value: "system/{{ .name }}"
      destination:
        name: in-cluster
        namespace: '{{ default .name (dig "namespace" "" .) }}'
      ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
      - group: apps
        kind: "*"
        jqPathExpressions:
        - .spec.template.spec.hostUsers
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        # - ServerSideApply=true
        - RespectIgnoreDifferences=true
        - PruneLast=true
        - PrunePropagationPolicy=foreground
        - SkipDryRunOnMissingResource=true
        # - RespectIgnoreDifferences=false
        - '{{ printf "%s=%s" "ServerSideApply" (dig "serverSideApply" "true" . | toString) }}'
