apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: logging-apps
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
  - list:
      elements:

        # - name: loki-stack
        #   namespace: logging
        #   serverSideApply: true
        # - name: promtail
        #   namespace: logging
        #   serverSideApply: true
        # - name: influxdb
        #   namespace: monitoring
        #   serverSideApply: true

        # - name: botkube
        #   namespace: monitoring
        #   serverSideApply: true

        # - name: karma
        #   namespace: monitoring
        #   serverSideApply: true

        # - name: eck-stack
        #   namespace: elastic-system
        #   helm:
        #     valueFiles:
        #     - "values.yaml"
        #   serverSideApply: true
        # - name: loki
        #   namespace: monitoring
        #   serverSideApply: true
        # helm:
        #   valueFiles:
        #   - "values.yaml"
        # - "manifest-dev.yaml"
        # - name: eck-stack
        #   namespace: elastic-system
        # serverSideApply: true

  template:
    metadata:
      name: "{{ .name }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "."
        # notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1001726711150"
        # argocd.argoproj.io/compare-options: '{{ printf "%s=%s" "ServerSideDiff" (dig "serverSideDiff" "false" . | toString) }}'
    spec:
      project: monitoring
      source:
        repoURL: https://github.com/donydonald1/rke2-baremetal-tf-ansible.git
        targetRevision: HEAD
        path: "gitops/logs/{{ .name }}"
        # plugin:
        #   name: avp-directory-include
        # env:
        #   - name: FILE_NAME
        #     value: "system/{{ .name }}"
      destination:
        name: in-cluster
        namespace: '{{ default .name (dig "namespace" "" .) }}'
      ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
      - group: apps
        kind: "*"
        jqPathExpressions:
        - .spec.template.spec.hostUsers
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        # - ServerSideApply=true
        - RespectIgnoreDifferences=true
        - PruneLast=true
        - PrunePropagationPolicy=foreground
        - SkipDryRunOnMissingResource=true
        # - RespectIgnoreDifferences=false
        - '{{ printf "%s=%s" "ServerSideApply" (dig "serverSideApply" "true" . | toString) }}'
