app-template:
  controllers:
    couchdb:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      statefulset:
        volumeClaimTemplates:
          - name: data
            accessMode: ReadWriteOnce
            size: 2Gi
            storageClass: "longhorn"
            globalMounts:
              - path: /opt/couchdb/data

      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          fsGroup: 568
          fsGroupChangePolicy: "OnRootMismatch"

      initContainers:
        init-config:
          image:
            repository: public.ecr.aws/docker/library/busybox
            tag: latest@sha256:db142d433cdde11f10ae479dbf92f3b13d693fd1c91053da9979728cceb1dc68
            pullPolicy: IfNotPresent
          command:
            - "/bin/sh"
            - "-c"
            - "cp /tmp/config/*.ini /opt/couchdb/etc/default.d/; ls -lrt /opt/couchdb/etc/default.d;"

      containers:
        couchdb:
          image:
            repository: public.ecr.aws/docker/library/couchdb
            tag: 3.4.2
          env:
            COUCHDB_USER:
              valueFrom:
                secretKeyRef:
                  name: couchdb-secret
                  key: couchdb-user
            COUCHDB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: couchdb-secret
                  key: couchdb-password
          resources:
            requests:
              cpu: 48m
              memory: 146M
            limits:
              memory: 5Gi

  service:
    app:
      controller: couchdb
      ports:
        http:
          port: 5984

  ingress:
    app:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod    
        cert-manager.io/duration: "2160h"
        cert-manager.io/renew-before: "720h"
      hosts:
        - host: "couchdb.dev.techsecoms.com"
          paths:
            - path: /
              service:
                identifier: app
                port: http
      tls:
        - hosts:
            - *host
          secretName: couchdb-cert-tls

  persistence:
    config:
      enabled: true
      type: configMap
      name: couchdb-configmap
      advancedMounts:
        couchdb:
          init-config:
            - path: /tmp/config
    config-storage:
      enabled: true
      type: emptyDir
      globalMounts:
        - path: /opt/couchdb/etc/default.d
