{{- if .Values.eso.enabled }}
{{- if eq .Values.eso.type "generic" }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.eso.secretStoreName }}
spec:
  provider:
    {{- with .Values.eso.generic.secretStore.providerConfig }}
      {{-  toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
