{{- if .Values.eso.enabled }}
{{- $secretName := .Values.eso.secretName }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-admin-ui
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
  - secretKey: root-user
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/minio
      metadataPolicy: None
      property: root-user
  - secretKey: root-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/minio
      metadataPolicy: None
      property: root-password
{{- end }}
