# {{- if .Values.eso.enabled }}
# {{- $secretName := .Values.eso.secretName }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-s3
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
  - secretKey: REGISTRY_STORAGE_S3_ACCESSKEY
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/harbor
      metadataPolicy: None
      property: REGISTRY_STORAGE_S3_ACCESSKEY
  - secretKey: REGISTRY_STORAGE_S3_SECRETKEY
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/harbor
      metadataPolicy: None
      property: REGISTRY_STORAGE_S3_SECRETKEY
# {{- end }}
