{{- if .Values.eso.enabled }}
{{- $secretName := .Values.eso.secretName }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/redis
        metadataPolicy: None
        property: redis-password
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/redis
        metadataPolicy: None
        property: redis-username
{{- end }}
