apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: minio-oidc
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: vault
    target:
        name: minio-oidc
    data:
      - secretKey: clientId
        remoteRef:
            key: minio
            property: client_id
      - secretKey: clientSecret
        remoteRef:
            key: minio
            property: client_secret