spegel:
  spegel:
    containerdSock: /run/k3s/containerd/containerd.sock
    containerdRegistryConfigPath: /var/lib/rancher/rke2/agent/etc/containerd/certs.d
    containerdContentPath: /var/lib/rancher/rke2/agent/containerd/io.containerd.content.v1.content
    containerdMirrorAdd: false
    registries:
    - https://cgr.dev
    - https://docker.io
    - https://ghcr.io
    - https://quay.io
    - https://mcr.microsoft.com
    - https://public.ecr.aws
    - https://gcr.io
    - https://registry.k8s.io
    - https://k8s.gcr.io
    - https://lscr.io
  serviceMonitor:
    enabled: true
  grafanaDashboard:
    enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 1Gi
